print ("Этапы эволюции человека")
a1 = input()
a2 = input()
a3 = input()
a4 = input()
a5 = input()
a6 = input()
print (a1, a2, a3, a4, a5, a6, sep = "=>")

print ("Этапы эволюции человека")
a1 = ("homo habilis")
a2 = ("homo erectus")
a3 = ("homo erectus2")
a4 = ("homo heidelbergensis")
a5 = ("Homo sapiens neanderthalensis")
a6 = ("homo sapiens")
print (a1, a2, a3, a4, a5, a6, sep = "=>")